train:
  model: "sovits"
  fp16_run: False
  log_interval: 200
  eval_interval: 1000
  seed: 1234
  epochs: 10000
  learning_rate: 1e-4
  betas: [0.8, 0.99]
  lr_decay: 0.999875
  init_lr_ratio: 1
  warmup_epochs: 0
  eps: 1e-9
  batch_size: 12
  c_mel: 45
  c_kl: 1.0
  port: 8001
#############################
data: 
  training_files: "files/train.txt"
  validation_files: "files/valid.txt"
  segment_size: 8000  # WARNING: base on hop_length
  max_wav_value: 32768.0
  sampling_rate: 16000
  filter_length: 512
  hop_length: 160
  win_length: 512
  mel_channels: 80
  mel_fmin: 0.0
  mel_fmax: None
#############################
vits:
  ppg_dim: 256
  spk_dim: 256
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
#############################
gen:
  upsample_input: 192
  upsample_rates: [5,4,2,2,2]
  upsample_kernel_sizes: [15,12,4,4,4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#############################
mpd:
  periods: [2,3,5,7,11]
  kernel_size: 5
  stride: 3
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
mrd:
  resolutions: "[(1024, 120, 600), (2048, 240, 1200), (512, 50, 240)]" # (filter_length, hop_length, win_length)
  use_spectral_norm: False
  lReLU_slope: 0.2
